### ISSUE TITLE
建议把Dockerfile中RUN语句整合一下

### ISSUE THREAD

**Issue by ENTNEAZ** [DistinctWind/visual-decaf-docker-run#1]
因为每次的RUN语句会在上一次的RUN之后创建新的一层layer 会导致image体积庞大
建议从：
```
RUN echo 1
RUN echo 2
```
改为:
```
RUN echo 1 && \
        echo 2
```

(当然小项目不在意这个也没什么关系 这也无关紧要其实)
[参考](https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better)

**Comment by chofuhoyu** [comment]
感谢你的建议，如果你也对Visual Decaf项目感兴趣，可以看看我们的[工作仓库](https://github.com/visual-decaf/decaf-compiler)，本仓库只是个试验场。

我计划在下一次docker版本更新到`VERSION 0.0.5`时采纳这个意见，如果你能在那边提出同样的Issue那就再好不过了：）
